rvm:
  - 2.1.2
  - 2.2.3
script:
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rspec
before_script:
  - psql -c 'create database so_test;' -U postgres
  - bundle exec rackup private_pub.ru -s thin -E production &
  - sleep 3